name: unity

on:
  push:
    branches:
      - master
      - 'support/*'
  pull_request: {}

concurrency:
  group: unity-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unity:
    name: Unity build

    strategy:
      fail-fast: false
      matrix:
        onoff:
          - ON
          - OFF

    runs-on: ubuntu-latest

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1

      - name: Restore/backup ccache
        id: ccache
        uses: actions/cache@v1
        with:
          path: ccache
          key: |-
            unity/${{ matrix.onoff }}-ccache-${{ hashFiles('ccache') }}

      - run: sudo apt-get install -y g++ libboost-all-dev libedit-dev ninja-build
      - run: sudo apt-get install -y ccache

      - run: >-
          cmake
          -GNinja
          -DCMAKE_C_COMPILER=/usr/lib/ccache/gcc
          -DCMAKE_CXX_COMPILER=/usr/lib/ccache/g++
          -DCMAKE_BUILD_TYPE=Debug
          -DICINGA2_UNITY_BUILD=${{ matrix.onoff }}
          -DICINGA2_USER=$(id -un)
          -DICINGA2_GROUP=$(id -gn)
          .

      - run: 'CCACHE_DIR="$(pwd)/ccache" ninja'
